// Dados para simular os parceiros
export const dadosParceiros = [
  {
    id: 1,
    habilitacao: "Parceiro",
    status: "Pendente",
    cnpj: "11.111.111/1000-00",
    nomeFantasia: "Nome 1",
    nomePontoFocal: "Fulano",
    razaoSocial: "Razão 1",
    naturezaJuridica: "Público",
    nomeResponsavel: "Beltrano Gonçalves",
    cidade: "Brasília",
    uf: "DF",
    email: "fulano@teste.com",
    endereco: "Bairro tal, Rua 1",
    cadastro: "2024-03-20T00:00",
    ultimaModificacao: "2024-03-21T00:00",
    telefone: "(00) 00000-0000",
    tipoDeServico: {
      VEP: true,
      VET: false,
      VJA: false,
      CUR: false,
      FPG: false,
      MPu: false,
      MPa: false,
    },
  },
  {
    id: 2,
    habilitacao: "Parceiro",
    status: "Pendente",
    cnpj: "22.222.222/1000-00",
    nomeFantasia: "Nome 2",
    nomePontoFocal: "Beltrano",
    razaoSocial: "Razão 2",
    naturezaJuridica: "Privado",
    nomeResponsavel: "Fulano",
    cidade: "Goiânia",
    uf: "GO",
    email: "beltraninho@teste.com",
    endereco: "Bairro tal, Rua 2",
    cadastro: "2024-03-03T00:00",
    ultimaModificacao: "2024-04-10T00:00",
    telefone: "(00) 00000-0000",
    tipoDeServico: {
      VEP: false,
      VET: true,
      VJA: false,
      CUR: false,
      FPG: false,
      MPu: false,
      MPa: false,
    },
  },
  {
    id: 3,
    habilitacao: "Parceiro",
    status: "Pendente",
    cnpj: "33.333.333/1000-00",
    nomeFantasia: "Nome 1",
    nomePontoFocal: "Fulano da Silva",
    razaoSocial: "Razão 1",
    naturezaJuridica: "Público",
    nomeResponsavel: "Beltrano",
    cidade: "Catalão",
    uf: "GO",
    email: "beltrano@teste.com",
    endereco: "Bairro num sei, Rua 10",
    cadastro: "2024-02-27T00:00",
    ultimaModificacao: "2024-03-15T00:00",
    telefone: "(00) 00000-0000",
    tipoDeServico: {
      VEP: false,
      VET: false,
      VJA: true,
      CUR: false,
      FPG: false,
      MPu: false,
      MPa: false,
    },
  },
  {
    id: 4,
    habilitacao: "Parceiro",
    status: "Pendente",
    cnpj: "44.444.444/1000-00",
    nomeFantasia: "Nome 3",
    nomePontoFocal: "Beltrano Gonçalves",
    razaoSocial: "Razão 1",
    naturezaJuridica: "Privado",
    nomeResponsavel: "Fulano da Silva",
    cidade: "Belo Horizonte",
    uf: "MG",
    email: "beltranogo@teste.com",
    endereco: "Bairro tal, Rua 1",
    cadastro: "2024-02-11T00:00",
    ultimaModificacao: "2024-02-13T00:00",
    telefone: "(00) 00000-0000",
    tipoDeServico: {
      VEP: true,
      VET: false,
      VJA: false,
      CUR: false,
      FPG: false,
      MPu: false,
      MPa: false,
    },
  },
  {
    id: 5,
    habilitacao: "Parceiro",
    status: "Pendente",
    cnpj: "55.555.555/1000-00",
    nomeFantasia: "Nome 2",
    nomePontoFocal: "Fulano Beltrano",
    razaoSocial: "Razão 1",
    naturezaJuridica: "Privado",
    nomeResponsavel: "Beltrano Fulano",
    cidade: "Brasília",
    uf: "DF",
    email: "fulanobeltrano@teste.com",
    endereco: "Bairro num sei, Rua 2",
    cadastro: "2024-03-20T00:00",
    ultimaModificacao: "2024-03-21T00:00",
    telefone: "(00) 00000-0000",
    tipoDeServico: {
      VEP: false,
      VET: true,
      VJA: true,
      CUR: false,
      FPG: false,
      MPu: false,
      MPa: false,
    },
  },
  {
    id: 6,
    habilitacao: "Parceiro",
    status: "Pendente",
    cnpj: "66.666.666/1000-00",
    nomeFantasia: "Nome 1",
    nomePontoFocal: "Fulano Bel",
    razaoSocial: "Razão 1",
    naturezaJuridica: "Privado",
    nomeResponsavel: "Be Fulano",
    cidade: "Brasília",
    uf: "DF",
    email: "fulanobel@teste.com",
    endereco: "Bairro sei la, Rua 1",
    cadastro: "2024-02-28T00:00",
    ultimaModificacao: "2024-03-10T00:00",
    tipoDeServico: {
      VEP: false,
      VET: true,
      VJA: false,
      CUR: false,
      FPG: false,
      MPu: false,
      MPa: false,
    },
  },
  {
    id: 7,
    habilitacao: "Parceiro",
    status: "Pendente",
    cnpj: "77.777.777/1000-00",
    nomeFantasia: "Nome 2",
    nomePontoFocal: "Fu Beltrano",
    razaoSocial: "Razão 1",
    naturezaJuridica: "Privado",
    nomeResponsavel: "Fulano",
    cidade: "Brasília",
    uf: "DF",
    email: "fubeltrano@teste.com",
    endereco: "Bairro sei la, Rua 5",
    cadastro: "2024-03-29T00:00",
    ultimaModificacao: "2024-04-21T00:00",
    tipoDeServico: {
      VEP: false,
      VET: false,
      VJA: false,
      CUR: false,
      FPG: true,
      MPu: false,
      MPa: false,
    },
  },
];
