// Dados para simular os parceiros
export const dadosParceirosPendentes = [
  {
    id: 1,
    habilitacao: "Parceiro",
    status: "Pendente",
    naturezaJuridica: "Público",
    cnpj: "11.111.111/1000-00",
    nomeFantasia: "República Comércio",
    razaoSocial: "República Comércio de Produtos Ltda",
    nomeResponsavel: "Bail Organa",
    email: "bail@republica.com",
    cidade: "Brasília",
    uf: "DF",
    nomePontoFocal: "Leia Organa",
    emailPontoFocal: "leia@republica.com",
    endereco: "Bairro Central, Rua Alderaan, 1",
    telefone: "(61) 00000-0000",
    dataCadastro: "2024-03-20T00:00",
    dataUltimaModificacao: "2024-03-21T00:00",
    tipoDeServico: {
      VEP: true,
      VET: false,
      VJA: false,
      CUR: false,
      FPG: false,
      MPu: false,
      MPa: false,
    },
  },
  {
    id: 2,
    habilitacao: "Parceiro",
    status: "Pendente",
    naturezaJuridica: "Privado",
    cnpj: "22.222.222/2000-00",
    nomeFantasia: "Academia Jedi",
    razaoSocial: "Academia Jedi Treinamentos Ltda",
    nomeResponsavel: "Anakin Skywalker",
    email: "anakin@jedi.com",
    cidade: "São Paulo",
    uf: "SP",
    nomePontoFocal: "Luke Skywalker",
    emailPontoFocal: "luke@jedi.com",
    endereco: "Bairro Norte, Rua Tatooine, 2",
    telefone: "(11) 11111-1111",
    dataCadastro: "2024-03-03T00:00",
    dataUltimaModificacao: "2024-04-10T00:00",
    tipoDeServico: {
      VEP: false,
      VET: true,
      VJA: false,
      CUR: false,
      FPG: false,
      MPu: false,
      MPa: false,
    },
  },
  {
    id: 3,
    habilitacao: "Parceiro",
    status: "Pendente",
    cnpj: "33.333.333/3000-00",
    naturezaJuridica: "Terceiro Setor",
    nomeFantasia: "Ferragens de Beskar",
    razaoSocial: "Ferragens de Beskar Ltda",
    nomeResponsavel: "Paz Vizsla",
    email: "paz@beskar.com",
    cidade: "Rio de Janeiro",
    uf: "RJ",
    nomePontoFocal: "Din Djarin",
    emailPontoFocal: "din@beskar.com",
    endereco: "Bairro Oeste, Rua Mandalore, 3",
    telefone: "(21) 22222-2222",
    dataCadastro: "2024-02-27T00:00",
    dataUltimaModificacao: "2024-03-15T00:00",
    tipoDeServico: {
      VEP: false,
      VET: false,
      VJA: true,
      CUR: false,
      FPG: false,
      MPu: false,
      MPa: false,
    },
  },
  {
    id: 4,
    habilitacao: "Parceiro",
    status: "Pendente",
    naturezaJuridica: "Público",
    cnpj: "44.444.444/4000-00",
    nomeFantasia: "Oráculo de Coruscant",
    razaoSocial: "Oráculo de Coruscant Consultoria Ltda",
    nomeResponsavel: "Ruwee Naberrie",
    email: "ruwee@oraculo.com",
    cidade: "Salvador",
    uf: "BA",
    nomePontoFocal: "Padmé Amidala",
    emailPontoFocal: "padme@oraculo.com",
    endereco: "Bairro Leste, Rua Naboo, 4",
    telefone: "(71) 33333-3333",
    dataCadastro: "2024-02-11T00:00",
    dataUltimaModificacao: "2024-02-13T00:00",
    tipoDeServico: {
      VEP: true,
      VET: false,
      VJA: false,
      CUR: false,
      FPG: false,
      MPu: false,
      MPa: false,
    },
  },
  {
    id: 5,
    habilitacao: "Parceiro",
    status: "Pendente",
    naturezaJuridica: "Privado",
    cnpj: "55.555.555/5000-00",
    nomeFantasia: "Falcon Transportes",
    razaoSocial: "Falcon Transportes de Cargas Ltda",
    nomeResponsavel: "Chewbacca",
    email: "chewbacca@falcon.com",
    cidade: "Porto Alegre",
    uf: "RS",
    nomePontoFocal: "Han Solo",
    emailPontoFocal: "han@falcon.com",
    endereco: "Bairro Sul, Rua Corellia, 5",
    telefone: "(51) 44444-4444",
    dataCadastro: "2024-03-20T00:00",
    dataUltimaModificacao: "2024-03-21T00:00",
    tipoDeServico: {
      VEP: false,
      VET: true,
      VJA: true,
      CUR: false,
      FPG: false,
      MPu: false,
      MPa: false,
    },
  },
  {
    id: 6,
    habilitacao: "Parceiro",
    status: "Pendente",
    naturezaJuridica: "Terceiro Setor",
    cnpj: "66.666.666/6000-00",
    nomeFantasia: "Sith Inovações",
    razaoSocial: "Sith Inovações Tecnológicas Ltda",
    nomeResponsavel: "Sheev Palpatine",
    email: "palpatine@sith.com",
    cidade: "Curitiba",
    uf: "PR",
    nomePontoFocal: "Darth Vader",
    emailPontoFocal: "vader@sith.com",
    endereco: "Bairro Escuro, Rua Mustafar, 6",
    telefone: "(41) 66666-6666",
    dataCadastro: "2024-02-28T00:00",
    dataUltimaModificacao: "2024-03-10T00:00",
    tipoDeServico: {
      VEP: false,
      VET: true,
      VJA: false,
      CUR: false,
      FPG: false,
      MPu: false,
      MPa: false,
    },
  },
  {
    id: 7,
    habilitacao: "Parceiro",
    status: "Pendente",
    naturezaJuridica: "Público",
    cnpj: "77.777.777/7000-00",
    nomeFantasia: "Cantina Mos Eisley",
    razaoSocial: "Cantina Mos Eisley Entretenimento Ltda",
    nomeResponsavel: "Dexter Jettster",
    email: "jettster@cantina.com",
    cidade: "Fortaleza",
    uf: "CE",
    nomePontoFocal: "Obi-Wan Kenobi",
    emailPontoFocal: "kenobi@cantina.com",
    endereco: "Bairro Duna, Rua Tatooine, 7",
    telefone: "(85) 77777-7777",
    dataCadastro: "2024-03-29T00:00",
    dataUltimaModificacao: "2024-04-21T00:00",
    tipoDeServico: {
      VEP: false,
      VET: false,
      VJA: false,
      CUR: false,
      FPG: true,
      MPu: false,
      MPa: false,
    },
  },
  {
    id: 8,
    habilitacao: "Parceiro",
    status: "Pendente",
    naturezaJuridica: "Privado",
    cnpj: "88.888.888/8000-00",
    nomeFantasia: "Caminho dos Clones",
    razaoSocial: "Caminho dos Clones Produções Ltda",
    nomeResponsavel: "Jango Fett",
    email: "jango@clones.com",
    cidade: "Manaus",
    uf: "AM",
    nomePontoFocal: "Boba Fett",
    emailPontoFocal: "boba@clones.com",
    endereco: "Bairro Floresta, Rua Kamino, 8",
    telefone: "(92) 88888-8888",
    dataCadastro: "2024-03-29T00:00",
    dataUltimaModificacao: "2024-04-21T00:00",
    tipoDeServico: {
      VEP: false,
      VET: false,
      VJA: false,
      CUR: false,
      FPG: true,
      MPu: false,
      MPa: false,
    },
  },
  {
    id: 9,
    habilitacao: "Parceiro",
    status: "Pendente",
    naturezaJuridica: "Terceiro Setor",
    cnpj: "99.999.999/9000-00",
    nomeFantasia: "HoloNet Serviços",
    razaoSocial: "HoloNet Serviços de Comunicação Ltda",
    nomeResponsavel: "Lobot",
    email: "lobot@holonet.com",
    cidade: "Recife",
    uf: "PE",
    nomePontoFocal: "Lando Calrissian",
    emailPontoFocal: "lando@holonet.com",
    endereco: "Bairro Cloud, Rua Bespin, 9",
    telefone: "(81) 99999-9999",
    dataCadastro: "2024-03-29T00:00",
    dataUltimaModificacao: "2024-04-21T00:00",
    tipoDeServico: {
      VEP: false,
      VET: false,
      VJA: false,
      CUR: false,
      FPG: true,
      MPu: false,
      MPa: false,
    },
  },
];

export const dadosPessoas = [
  {
    id: 1,
    status: "Pendente",
    pcd: "Sim",
    email: "bail@republica.com",
    criteriosDaVaga: "Sim",
  },
  {
    id: 2,
    status: "Pendente",
    pcd: "Não",
    email: "anakin@jedi.com",
    criteriosDaVaga: "Sim",
  },
  {
    id: 3,
    status: "Pendente",
    pcd: "Não",
    email: "paz@beskar.com",
    criteriosDaVaga: "Não",
  },
  {
    id: 4,
    status: "Pendente",
    pcd: "Não",
    email: "ruwee@oraculo.com",
    criteriosDaVaga: "Sim",
  },
  {
    id: 5,
    status: "Pendente",
    pcd: "Sim",
    email: "chewbacca@falcon.com",
    criteriosDaVaga: "Sim",
  },
  {
    id: 6,
    status: "Pendente",
    pcd: "Não",
    email: "palpatine@sith.com",
    criteriosDaVaga: "Não",
  },
  {
    id: 7,
    status: "Pendente",
    pcd: "Não",
    email: "jettster@cantina.com",
    criteriosDaVaga: "Sim",
  },
  {
    id: 8,
    status: "Pendente",
    pcd: "Sim",
    email: "jango@clones.com",
    criteriosDaVaga: "Não",
  },
  {
    id: 9,
    status: "Pendente",
    pcd: "Sim",
    email: "lobot@holonet.com",
    criteriosDaVaga: "Sim",
  },
];

export const tabelaVagas = [
  {
    id: 1,
    nome: "Desenvolvedor Front-end",
    quantidade: 3,
    descricao: "Desenvolvimento de interfaces web",
    salario: "R$ 6.000,00",
    dataCadastro: "2024-05-01",
    vigencia: 30,
  },
  {
    id: 2,
    nome: "Analista de Dados",
    quantidade: 2,
    descricao: "Análise e interpretação de dados",
    salario: "R$ 7.500,00",
    dataCadastro: "2024-04-25",
    vigencia: 60,
  },
  {
    id: 3,
    nome: "Gerente de Projetos",
    quantidade: 1,
    descricao: "Gestão de projetos e equipes",
    salario: "R$ 9.000,00",
    dataCadastro: "2024-04-15",
    vigencia: 45,
  },
  {
    id: 4,
    nome: "Designer UX/UI",
    quantidade: 2,
    descricao: "Criação de interfaces de usuário",
    salario: "R$ 5.500,00",
    dataCadastro: "2024-05-10",
    vigencia: 90,
  },
];

export const dadosParceirosAprovados = [
  {
    id: 1,
    habilitacao: "Parceiro",
    status: "Aprovado",
    naturezaJuridica: "Privado",
    cnpj: "22.222.222/2000-00",
    nomeFantasia: "Pokémon Center",
    razaoSocial: "Pokémon Center Ltda",
    nomeResponsavel: "Ash Ketchum",
    email: "ash@pokemoncenter.com",
    cidade: "Pallet Town",
    uf: "SP",
    nomePontoFocal: "Misty Waterflower",
    emailPontoFocal: "misty@pokemoncenter.com",
    endereco: "Rua Pikachu, 25",
    telefone: "(11) 22222-2222",
    dataCadastro: "2024-04-10T00:00",
    dataUltimaModificacao: "2024-04-11T00:00",
    tipoDeServico: {
      VEP: true,
      VET: true,
      VJA: false,
      CUR: true,
      FPG: false,
      MPu: false,
      MPa: false,
    },
  },
  {
    id: 2,
    habilitacao: "Parceiro",
    status: "Aprovado",
    naturezaJuridica: "Terceiro Setor",
    cnpj: "33.333.333/3000-00",
    nomeFantasia: "Silph Co.",
    razaoSocial: "Silph Company Ltda",
    nomeResponsavel: "Giovanni",
    email: "giovanni@silphco.com",
    cidade: "Saffron City",
    uf: "SP",
    nomePontoFocal: "Jessie",
    emailPontoFocal: "jessie@silphco.com",
    endereco: "Avenida Rocket, 100",
    telefone: "(11) 33333-3333",
    dataCadastro: "2024-02-15T00:00",
    dataUltimaModificacao: "2024-02-16T00:00",
    tipoDeServico: {
      VEP: false,
      VET: true,
      VJA: true,
      CUR: false,
      FPG: true,
      MPu: false,
      MPa: true,
    },
  },
  {
    id: 3,
    habilitacao: "Parceiro",
    status: "Aprovado",
    naturezaJuridica: "Público",
    cnpj: "44.444.444/4000-00",
    nomeFantasia: "Pewter Gym",
    razaoSocial: "Pewter Gym Ltda",
    nomeResponsavel: "Brock Harrison",
    email: "brock@pewtergym.com",
    cidade: "Pewter City",
    uf: "RJ",
    nomePontoFocal: "Forrest Harrison",
    emailPontoFocal: "forrest@pewtergym.com",
    endereco: "Rua Onix, 50",
    telefone: "(21) 44444-4444",
    dataCadastro: "2024-01-20T00:00",
    dataUltimaModificacao: "2024-01-21T00:00",
    tipoDeServico: {
      VEP: true,
      VET: false,
      VJA: true,
      CUR: true,
      FPG: true,
      MPu: false,
      MPa: false,
    },
  },
  {
    id: 4,
    habilitacao: "Parceiro",
    status: "Aprovado",
    naturezaJuridica: "Privado",
    cnpj: "55.555.555/5000-00",
    nomeFantasia: "Cerulean Gym",
    razaoSocial: "Cerulean Gym Ltda",
    nomeResponsavel: "Misty Waterflower",
    email: "misty@ceruleangym.com",
    cidade: "Cerulean City",
    uf: "RJ",
    nomePontoFocal: "Daisy Waterflower",
    emailPontoFocal: "daisy@ceruleangym.com",
    endereco: "Rua Starmie, 75",
    telefone: "(21) 55555-5555",
    dataCadastro: "2024-03-05T00:00",
    dataUltimaModificacao: "2024-03-06T00:00",
    tipoDeServico: {
      VEP: false,
      VET: true,
      VJA: false,
      CUR: true,
      FPG: true,
      MPu: true,
      MPa: false,
    },
  },
  {
    id: 5,
    habilitacao: "Parceiro",
    status: "Aprovado",
    naturezaJuridica: "Terceiro Setor",
    cnpj: "66.666.666/6000-00",
    nomeFantasia: "Vermilion Gym",
    razaoSocial: "Vermilion Gym Ltda",
    nomeResponsavel: "Lt. Surge",
    email: "lt.surge@vermiliongym.com",
    cidade: "Vermilion City",
    uf: "SP",
    nomePontoFocal: "Raichu",
    emailPontoFocal: "raichu@vermiliongym.com",
    endereco: "Rua Thunderbolt, 200",
    telefone: "(11) 66666-6666",
    dataCadastro: "2024-04-01T00:00",
    dataUltimaModificacao: "2024-04-02T00:00",
    tipoDeServico: {
      VEP: true,
      VET: true,
      VJA: false,
      CUR: false,
      FPG: true,
      MPu: true,
      MPa: true,
    },
  },
];

export const dadosParceirosReprovados = [
  {
    id: 1,
    habilitacao: "Parceiro",
    status: "Reprovado",
    naturezaJuridica: "Público",
    cnpj: "77.777.777/7000-00",
    nomeFantasia: "Nação do Fogo Comércio",
    razaoSocial: "Nação do Fogo Comércio Ltda",
    nomeResponsavel: "Zuko",
    email: "zuko@nacaodofogo.com",
    cidade: "Capital da Nação do Fogo",
    uf: "RJ",
    nomePontoFocal: "Iroh",
    emailPontoFocal: "iroh@nacaodofogo.com",
    endereco: "Avenida Dragão Azul, 100",
    telefone: "(21) 77777-7777",
    dataCadastro: "2024-01-15T00:00",
    dataUltimaModificacao: "2024-01-16T00:00",
    tipoDeServico: {
      VEP: false,
      VET: false,
      VJA: false,
      CUR: false,
      FPG: true,
      MPu: false,
      MPa: true,
    },
  },
  {
    id: 2,
    habilitacao: "Parceiro",
    status: "Reprovado",
    naturezaJuridica: "Privado",
    cnpj: "88.888.888/8000-00",
    nomeFantasia: "Pólo do Sul Exportações",
    razaoSocial: "Pólo do Sul Exportações Ltda",
    nomeResponsavel: "Katara",
    email: "katara@polodosul.com",
    cidade: "Pólo do Sul",
    uf: "SP",
    nomePontoFocal: "Sokka",
    emailPontoFocal: "sokka@polodosul.com",
    endereco: "Rua Esquimó, 50",
    telefone: "(11) 88888-8888",
    dataCadastro: "2024-02-20T00:00",
    dataUltimaModificacao: "2024-02-21T00:00",
    tipoDeServico: {
      VEP: false,
      VET: true,
      VJA: true,
      CUR: false,
      FPG: false,
      MPu: true,
      MPa: false,
    },
  },
  {
    id: 3,
    habilitacao: "Parceiro",
    status: "Reprovado",
    naturezaJuridica: "Terceiro Setor",
    cnpj: "99.999.999/9000-00",
    nomeFantasia: "Ba Sing Se Comércio",
    razaoSocial: "Ba Sing Se Comércio Ltda",
    nomeResponsavel: "Toph Beifong",
    email: "toph@basingse.com",
    cidade: "Ba Sing Se",
    uf: "MG",
    nomePontoFocal: "Lin Beifong",
    emailPontoFocal: "lin@basingse.com",
    endereco: "Rua Terra, 75",
    telefone: "(31) 99999-9999",
    dataCadastro: "2024-03-10T00:00",
    dataUltimaModificacao: "2024-03-11T00:00",
    tipoDeServico: {
      VEP: true,
      VET: false,
      VJA: false,
      CUR: true,
      FPG: false,
      MPu: false,
      MPa: true,
    },
  },
  {
    id: 4,
    habilitacao: "Parceiro",
    status: "Reprovado",
    naturezaJuridica: "Privado",
    cnpj: "10.000.000/1000-00",
    nomeFantasia: "República Unida de Negócios",
    razaoSocial: "República Unida de Negócios Ltda",
    nomeResponsavel: "Korra",
    email: "korra@republicaunida.com",
    cidade: "Cidade República",
    uf: "SP",
    nomePontoFocal: "Asami Sato",
    emailPontoFocal: "asami@republicaunida.com",
    endereco: "Avenida Avatar, 200",
    telefone: "(11) 10000-1000",
    dataCadastro: "2024-04-01T00:00",
    dataUltimaModificacao: "2024-04-02T00:00",
    tipoDeServico: {
      VEP: true,
      VET: true,
      VJA: false,
      CUR: false,
      FPG: false,
      MPu: true,
      MPa: false,
    },
  },
  {
    id: 5,
    habilitacao: "Parceiro",
    status: "Reprovado",
    naturezaJuridica: "Público",
    cnpj: "11.111.111/1100-00",
    nomeFantasia: "Tribo da Água Comércio",
    razaoSocial: "Tribo da Água Comércio Ltda",
    nomeResponsavel: "Kya",
    email: "kya@triboagua.com",
    cidade: "Pólo do Norte",
    uf: "RJ",
    nomePontoFocal: "Tonraq",
    emailPontoFocal: "tonraq@triboagua.com",
    endereco: "Rua Gelo, 300",
    telefone: "(21) 11111-1111",
    dataCadastro: "2024-05-05T00:00",
    dataUltimaModificacao: "2024-05-06T00:00",
    tipoDeServico: {
      VEP: false,
      VET: true,
      VJA: true,
      CUR: true,
      FPG: false,
      MPu: false,
      MPa: true,
    },
  },
];
