// Dados para simular os parceiros
export const dadosParceiros = [
  {
    id: 1,
    habilitacao: "Parceiro",
    status: "Pendente",
    naturezaJuridica: "Público",
    cnpj: "11.111.111/1000-00",
    nomeFantasia: "República Comércio",
    nomePontoFocal: "Leia Organa",
    razaoSocial: "República Comércio de Produtos Ltda",
    nomeResponsavel: "Bail Organa",
    cidade: "Brasília",
    uf: "DF",
    email: "leia@republica.com",
    endereco: "Bairro Central, Rua Alderaan, 1",
    telefone: "(61) 00000-0000",
    dataCadastro: "2024-03-20T00:00",
    dataUltimaModificacao: "2024-03-21T00:00",
    tipoDeServico: {
      VEP: true,
      VET: false,
      VJA: false,
      CUR: false,
      FPG: false,
      MPu: false,
      MPa: false,
    },
  },
  {
    id: 2,
    habilitacao: "Parceiro",
    status: "Pendente",
    naturezaJuridica: "Privado",
    cnpj: "22.222.222/2000-00",
    nomeFantasia: "Academia Jedi",
    nomePontoFocal: "Luke Skywalker",
    razaoSocial: "Academia Jedi Treinamentos Ltda",
    nomeResponsavel: "Anakin Skywalker",
    cidade: "São Paulo",
    uf: "SP",
    email: "luke@jedi.com",
    endereco: "Bairro Norte, Rua Tatooine, 2",
    telefone: "(11) 11111-1111",
    dataCadastro: "2024-03-03T00:00",
    dataUltimaModificacao: "2024-04-10T00:00",
    tipoDeServico: {
      VEP: false,
      VET: true,
      VJA: false,
      CUR: false,
      FPG: false,
      MPu: false,
      MPa: false,
    },
  },
  {
    id: 3,
    habilitacao: "Parceiro",
    status: "Pendente",
    naturezaJuridica: "Terceiro Setor",
    nomeFantasia: "Ferragens de Beskar",
    nomePontoFocal: "Din Djarin",
    razaoSocial: "Ferragens de Beskar Ltda",
    nomeResponsavel: "Paz Vizsla",
    cidade: "Rio de Janeiro",
    uf: "RJ",
    email: "din@beskar.com",
    endereco: "Bairro Oeste, Rua Mandalore, 3",
    telefone: "(21) 22222-2222",
    dataCadastro: "2024-02-27T00:00",
    dataUltimaModificacao: "2024-03-15T00:00",
    tipoDeServico: {
      VEP: false,
      VET: false,
      VJA: true,
      CUR: false,
      FPG: false,
      MPu: false,
      MPa: false,
    },
  },
  {
    id: 4,
    habilitacao: "Parceiro",
    status: "Pendente",
    naturezaJuridica: "Público",
    cnpj: "44.444.444/4000-00",
    nomeFantasia: "Oráculo de Coruscant",
    nomePontoFocal: "Padmé Amidala",
    razaoSocial: "Oráculo de Coruscant Consultoria Ltda",
    nomeResponsavel: "Ruwee Naberrie",
    cidade: "Salvador",
    uf: "BA",
    email: "padme@oraculo.com",
    endereco: "Bairro Leste, Rua Naboo, 4",
    telefone: "(71) 33333-3333",
    dataCadastro: "2024-02-11T00:00",
    dataUltimaModificacao: "2024-02-13T00:00",
    tipoDeServico: {
      VEP: true,
      VET: false,
      VJA: false,
      CUR: false,
      FPG: false,
      MPu: false,
      MPa: false,
    },
  },
  {
    id: 5,
    habilitacao: "Parceiro",
    status: "Pendente",
    naturezaJuridica: "Privado",
    cnpj: "55.555.555/5000-00",
    nomeFantasia: "Falcon Transportes",
    nomePontoFocal: "Han Solo",
    razaoSocial: "Falcon Transportes de Cargas Ltda",
    nomeResponsavel: "Chewbacca",
    cidade: "Porto Alegre",
    uf: "RS",
    email: "han@falcon.com",
    endereco: "Bairro Sul, Rua Corellia, 5",
    telefone: "(51) 44444-4444",
    dataCadastro: "2024-03-20T00:00",
    dataUltimaModificacao: "2024-03-21T00:00",
    tipoDeServico: {
      VEP: false,
      VET: true,
      VJA: true,
      CUR: false,
      FPG: false,
      MPu: false,
      MPa: false,
    },
  },
  {
    id: 6,
    habilitacao: "Parceiro",
    status: "Pendente",
    naturezaJuridica: "Terceiro Setor",
    cnpj: "66.666.666/6000-00",
    nomeFantasia: "Sith Inovações",
    nomePontoFocal: "Darth Vader",
    razaoSocial: "Sith Inovações Tecnológicas Ltda",
    nomeResponsavel: "Sheev Palpatine",
    cidade: "Curitiba",
    uf: "PR",
    email: "vader@sith.com",
    endereco: "Bairro Escuro, Rua Mustafar, 6",
    telefone: "(41) 66666-6666",
    dataCadastro: "2024-02-28T00:00",
    dataUltimaModificacao: "2024-03-10T00:00",
    tipoDeServico: {
      VEP: false,
      VET: true,
      VJA: false,
      CUR: false,
      FPG: false,
      MPu: false,
      MPa: false,
    },
  },
  {
    id: 7,
    habilitacao: "Parceiro",
    status: "Pendente",
    naturezaJuridica: "Público",
    cnpj: "77.777.777/7000-00",
    nomeFantasia: "Cantina Mos Eisley",
    nomePontoFocal: "Obi-Wan Kenobi",
    razaoSocial: "Cantina Mos Eisley Entretenimento Ltda",
    nomeResponsavel: "Dexter Jettster",
    cidade: "Fortaleza",
    uf: "CE",
    email: "kenobi@cantina.com",
    endereco: "Bairro Duna, Rua Tatooine, 7",
    telefone: "(85) 77777-7777",
    dataCadastro: "2024-03-29T00:00",
    dataUltimaModificacao: "2024-04-21T00:00",
    tipoDeServico: {
      VEP: false,
      VET: false,
      VJA: false,
      CUR: false,
      FPG: true,
      MPu: false,
      MPa: false,
    },
  },
  {
    id: 8,
    habilitacao: "Parceiro",
    status: "Pendente",
    naturezaJuridica: "Privado",
    cnpj: "88.888.888/8000-00",
    nomeFantasia: "Caminho dos Clones",
    nomePontoFocal: "Boba Fett",
    razaoSocial: "Caminho dos Clones Produções Ltda",
    nomeResponsavel: "Jango Fett",
    cidade: "Manaus",
    uf: "AM",
    email: "boba@clones.com",
    endereco: "Bairro Floresta, Rua Kamino, 8",
    telefone: "(92) 88888-8888",
    dataCadastro: "2024-03-29T00:00",
    dataUltimaModificacao: "2024-04-21T00:00",
    tipoDeServico: {
      VEP: false,
      VET: false,
      VJA: false,
      CUR: false,
      FPG: true,
      MPu: false,
      MPa: false,
    },
  },
  {
    id: 9,
    habilitacao: "Parceiro",
    status: "Pendente",
    naturezaJuridica: "Terceiro Setor",
    cnpj: "99.999.999/9000-00",
    nomeFantasia: "HoloNet Serviços",
    nomePontoFocal: "Lando Calrissian",
    razaoSocial: "HoloNet Serviços de Comunicação Ltda",
    nomeResponsavel: "Lobot",
    cidade: "Recife",
    uf: "PE",
    email: "lando@holonet.com",
    endereco: "Bairro Cloud, Rua Bespin, 9",
    telefone: "(81) 99999-9999",
    dataCadastro: "2024-03-29T00:00",
    dataUltimaModificacao: "2024-04-21T00:00",
    tipoDeServico: {
      VEP: false,
      VET: false,
      VJA: false,
      CUR: false,
      FPG: true,
      MPu: false,
      MPa: false,
    },
  },
];
